name: "⚙️ configuration: Cambios de Configuración"
description: "Solicitar cambios en la configuración del proyecto."
title: "[Chore] "
labels: ["configuration"]
body:
  - type: markdown
    attributes:
      value: |
        # **⚙️ configuration: Cambios de Configuración**

  - type: textarea
    id: configuration-description
    attributes:
      label: "Descripción del Cambio"
      description: "Explica los cambios de configuración necesarios y su impacto en el proyecto."
    validations:
      required: true

  - type: textarea
    id: affected-modules
    attributes:
      label: "Módulos Afectados"
      description: "Especifica los módulos que se verán afectados por el cambio de configuración."
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: "Comentarios Adicionales"
      description: "Añade cualquier comentario adicional o contexto relacionado con los cambios propuestos."
    validations:
      required: false
