name: " configuration: Cambios de Configuración"
description: "Solicitar cambios en la configuración del proyecto."
labels: ["configuration"]
body:
  - type: markdown
    attributes:
      value: |
        # ** configuration: Cambios de Configuración**
