name: "⚙️ configuration: Cambios de Configuración"
about: "Solicitar cambios en la configuración del proyecto"
title: "[Chore]"
labels: "configuration"
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        # **⚙️ configuration: Cambios de Configuración**
  - type: textarea
    attributes:
      label: "Descripción."
      description: "Explica los cambios de configuración requeridos y su impacto"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Modulos afectados"
      description: "Lista de modulos afectados por el cambio."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Comentarios adicionales"
      description: "Cualquier comentario adicional que quieras agregar."
