name: "📚 documentation: Actualización de Documentación"
about: "Actualizar o mejorar la documentación"
title: "[Documentation]"
labels: "documentation"
assignees: ""

body:
  -type: markdown
    attributes:
      value: |
        # **📚 documentation: Actualización de Documentación**

  - type: textarea
    attributes:
        label: "Descripción."
        description: "Explica los cambios de documentación requeridos y su impacto"
    validations:
        required: true