name: "🐛 fix: Corrección de Error"
about: "Reportar un error en el proyecto"
title: "[Fix]"
labels: "fix"
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        # **🐛 fix: Corrección de Error**
  
  - type: textarea
    attributes:
        label: "Descripción."
        description: "Explica el error que encontraste y su impacto"
    validations:
        required: true

  - type: textarea
    atributes:
        label: "Modulos afectados"
        description: "Lista de modulos afectados por el error."
    validations:
        required: true

  - type: textarea
    atributes:
        label: "Pasos para reproducir"
        description: "Lista de pasos para reproducir el error."
    validations:
        required: true

  - type: textarea
    atributes:
        label: "Comentarios adicionales"
        description: "Cualquier comentario adicional que quieras agregar."