name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize]
  release:
    types: [published]

jobs:

  commits-syntax-checker:
    uses: ./.github/workflows/commits.yml

  tests:
    needs: commits-syntax-checker
    uses: ./.github/workflows/tests.yml

  codacy:
    needs: tests
    uses: ./.github/workflows/codacy.yml

  sonar-cloud:
    needs: tests
    uses: ./.github/workflows/sonar-cloud.yml

  validate-main-branch:
    name: Validate Main Branch
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - run: echo "Push to main branch detected."

  deploy:
    needs: validate-main-branch
    uses: ./.github/workflows/deploy.yml

