name: Codacy Analysis

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Environment Variable
        run: echo "Token- $CODACY_PROJECT_TOKEN"
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 

      - name: Install Dependencies
        run: pnpm install

      - name: Run tests with Jest and collect coverage
        run: pnpm test
  
      - name: Upload coverage to Codacy
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
          npx codacy-coverage --coverage-xml=coverage/lcov-report/lcov-report.xml --token=${{ secrets.CODACY_PROJECT_TOKEN }}
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
