name: Codacy CI

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug Enviroment Variable
      run: echo "Token- $CODACY_PROJECT_TOKEN"
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install pnpm
      run: npm install -g pnpm
        
    - name: Install dependencies
      run: |
        pnpm store prune
        pnpm install

    - name: Test and coverage
      run: pnpm jest --coverage
    
    - name: Setup pnpm global bin directory
      run: |
        mkdir -p ~/.pnpm-global/bin
        echo "export PNPM_HOME=~/.pnpm-global" >> ~/.bashrc
        echo "export PATH=\$PNPM_HOME/bin:\$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Install Codacy Coverage Reporter
      run: pnpm install -g codacy-coverage-reporter

    - name: Upload coverage to Codacy
      run: |
        pnpm codacy-coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}