name: 
  
on:
 workflow_call:
  secrets:
    SONAR_TOKEN:
      required: true

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: |
          pnpm store prune
          pnpm install

      - name: Test and coverage
        run: pnpm jest --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}