name: 
  
on:
 workflow_call:
  secrets:
    SONAR_TOKEN:
      required: true
    SONAR_PROJECT_KEY:
      required: true
    SONAR_ORG:
      required: true

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: |
          pnpm store prune
          pnpm install

      - name: Test and coverage
        run: pnpm jest --coverage

      - name: Install SonarCloud Scanner
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}